
- name: create cornell_oidc.json
  template:
    src: cornell_oidc.json.j2
    dest: /opt/dv/cornell_oidc.json
  register: cornell_oidc_json

- name: configure cornell_oidc login
  uri:
    url: "{{ dataverse.api.location }}/admin/authenticationProviders"
    method: POST
    src: /opt/dv/cornell_oidc.json
    remote_src: true
    body_format: json
    status_code: 201
  when: cornell_oidc_json.changed
